project_name: gpggen
builds:
  - id: gpggen
    main: .
    goos:
      - windows
      - linux
    goarch:
      - amd64
    ldflags: -s -w
    targets:
      - windows_amd64
      - linux_amd64
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - COPYING
    - README.md
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
changelog:
  skip: true
release:
  github:
    owner: 4thel00z
    name: gpggen
    draft: false
    prerelease: false
